### ISSUE TITLE
Browser autocomplete (e.g. of email) broken for main form

### ISSUE THREAD

**Issue by sbliven** [eppic-team/eppic-wui#26]
Firefox auto-suggests completions for fields like the email address. These can normally be chosen by typing down to select the desired completion and pressing enter, or by clicking the proper element.

This doesn't work on the EPPIC submission form. Typing enter will sometimes give an error (e.g. invalid email address), or is sometimes ignored.

Mac OS 10.9, Firefox 33.1

**Comment by josemduarte** [comment]
Moved to eppic project
